source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QwikJson_Example', :exclusive => true do
  pod 'QwikJson', :path => '../'
end

target 'QwikJson_Tests', :exclusive => true do
  pod 'QwikJson', :path => '../'

  
end
